name: payroll_viewer
description: Mobile app for NCCA. Payroll pdf viewer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  syncfusion_flutter_pdfviewer: ^22.2.7
  form_validator: ^2.1.1
  flutter_inner_shadow: ^0.0.1
  flutter_pdfview: ^1.3.1
  http: ^1.1.0
  file_picker: ^5.3.4
  path: ^1.8.3
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/ncca_logo.png
    - assets/images/ncca_compact_logo.png
    - assets/images/ncca_footer.png
    - assets/images/background.png
    - assets/elements/blue_corner_spot.png
    - assets/elements/orange_corner_spot.png
    - assets/elements/yellow_edge_spot.png
    - assets/elements/security_icon.png
    - assets/elements/email_sent_icon.png
    - assets/elements/terms_icon.png
    - assets/elements/pdf_icon.png
    - assets/payroll.pdf
